if: (type = push AND branch IN (master, dev)) OR (type = pull_request AND NOT branch =~ /no-ci/)

language: go

install:
  - go get -d -t -v ./...
  - go get -v golang.org/x/lint/golint
  - ./scripts/install-frontend.sh

matrix:
  include:
    - name: "go1.13.x-linux"
      go: 1.13.x
      os: linux
      script: go test ./...
    - name: "go1.14.x-linux"
      go: 1.14.x
      os: linux
      script: go test ./...
    - name: "go1.13.x-linux-race"
      go: 1.13.x
      os: linux
      script: go test -race ./...
    - name "frontend"
      os: linux
      script: ./scripts/build-frontend.sh
