"on":
    push:
        branches:
            - master
name: Deploy to frontend
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: frontend
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: 9d649a49-367c-4b28-b200-85c464eca32b
                PORTER_HOST: https://cathy.withporter.run
                PORTER_PROJECT: "1"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1180061925 }}
